build:
    environment:
        php: '7.3.20'
        node: 'v12.18.2'

    dependencies:
        override:
            - npm rebuild
            - npm install
            - composer install --ignore-platform-reqs --no-interaction --no-scripts

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
