build:
    environment:
        php: '8.0.19'

    tests:
        override:
            - true # disable test execution on scrutinizer

    dependencies:
        override:
            - true

    nodes:
        analysis:
            requires:
                - branch: /^master$|^(bugfix|hotfix|beta)\/.+|^feature\/[a-z]+-\d+\/(master|dev)-.+|^feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev)-.+/
            tests:
                override:
                    - php-scrutinizer-run
