build:
    environment:
        php: '7.3.20'
        node: 'v12.18.2'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                requires:
                    - branch: master
                    - branch: /feature\/[a-z]+-\d+\/(master|dev).+|feature\/[a-z]+-\d+\/[a-z]+-\d+\/(master|dev).+/
                    - branch: /(bugfix|hotfix|beta)\/.+/
                override:
                    - php-scrutinizer-run
